//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserTicket
    {
        public int userTicketId { get; set; }
        public Nullable<int> ticketId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> ticketDate { get; set; }
        public Nullable<System.DateTime> ticketEndDate { get; set; }
    }
}
